"""A1 reaction taxonomy and legacy compatibility helpers."""

A1_REACTION_CLEAN_HOLD = "A1_REACTION_CLEAN_HOLD"
A1_REACTION_FAST_CLEAN_HOLD = "A1_REACTION_FAST_CLEAN_HOLD"
A1_REACTION_SWEEP_RECLAIM_RETEST = "A1_REACTION_SWEEP_RECLAIM_RETEST"
A1_REACTION_SWEEP_RECLAIM_DIRECT = "A1_REACTION_SWEEP_RECLAIM_DIRECT"
A1_REACTION_SWEEP_RECLAIM_NO_RETEST = "A1_REACTION_SWEEP_RECLAIM_NO_RETEST"
A1_REACTION_SWEEP_NO_RECLAIM = "A1_REACTION_SWEEP_NO_RECLAIM"
A1_REACTION_BREAKOUT_AWAY = "A1_REACTION_BREAKOUT_AWAY"
A1_REACTION_FAILED_RECLAIM = "A1_REACTION_FAILED_RECLAIM"
A1_REACTION_OPPOSITE_A1_CONFLICT = "A1_REACTION_OPPOSITE_A1_CONFLICT"
A1_REACTION_DELAYED_EXPANSION = "A1_REACTION_DELAYED_EXPANSION"
A1_REACTION_NO_RESPONSE = "A1_REACTION_NO_RESPONSE"
A1_REACTION_TIMEOUT = "A1_REACTION_TIMEOUT"
A1_REACTION_UNKNOWN = "A1_REACTION_UNKNOWN"

_LEGACY_TO_A1 = {
    "CLEAN_HOLD": A1_REACTION_CLEAN_HOLD,
    "SWEEP_RECLAIM": A1_REACTION_SWEEP_RECLAIM_RETEST,
    "BELOW_ZONE_ABSORPTION": A1_REACTION_SWEEP_RECLAIM_DIRECT,
}


def normalize_a1_reaction_type(raw_type: str, legacy_phase2_type: str = "") -> str:
    value = str(raw_type or "").strip()
    if value.startswith("A1_REACTION_"):
        return value
    if value in _LEGACY_TO_A1:
        return _LEGACY_TO_A1[value]
    legacy = str(legacy_phase2_type or "").strip()
    if legacy in _LEGACY_TO_A1:
        return _LEGACY_TO_A1[legacy]
    return A1_REACTION_UNKNOWN


def legacy_phase2_type_for_reaction(a1_reaction_type: str) -> str:
    value = str(a1_reaction_type or "").strip()
    if value == A1_REACTION_CLEAN_HOLD:
        return "CLEAN_HOLD"
    if value in {
        A1_REACTION_SWEEP_RECLAIM_RETEST,
        A1_REACTION_SWEEP_RECLAIM_DIRECT,
        A1_REACTION_SWEEP_RECLAIM_NO_RETEST,
    }:
        return "SWEEP_RECLAIM"
    return "UNKNOWN_RESEARCH"
