#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import annotations

import argparse
import sys
from datetime import datetime
from pathlib import Path
from typing import Any
from zoneinfo import ZoneInfo

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src.research.a1_edge.dataset_exporter import A1EdgeDatasetExporter
from src.research.a1_edge.forward_metrics import A1ForwardMetricsAnalyzer
from src.research.a1_edge.hypothesis_simulator import A1HypothesisSimulator
from src.research.a1_edge.io_utils import ensure_dir, parse_windows, read_kline_csv
from src.research.a1_edge.random_baseline import A1RandomBaselineComparator, RandomBaselineSampler
from src.research.a1_edge.report_builder import A1EdgeReportBuilder


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "V6.3.10 A1 Edge Validation Suite. Offline-only: intentionally not imported "
            "by main.py. Run main.py shadow first to collect A1 reaction JSONL, then use "
            "this CLI for offline analysis."
        )
    )
    parser.add_argument("--events", required=True, help="A1 events JSONL or CSV path generated by shadow run or supplied offline")
    parser.add_argument("--klines", required=True, help="1m kline CSV path")
    parser.add_argument(
        "--kline-timezone",
        default="Asia/Shanghai",
        help=(
            "Timezone for kline CSV timestamps that have no timezone. If your kline CSV timestamp is local "
            "Beijing time like 2026-05-21 20:00:00, use --kline-timezone Asia/Shanghai."
        ),
    )
    parser.add_argument("--out", default="reports/a1_edge", help="Output directory")
    parser.add_argument("--symbol", default="ETH-USDT-SWAP", help="Default symbol when events do not contain one")
    parser.add_argument("--random-samples-per-event", type=int, default=10)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--min-risk-u", type=float, default=1.0)
    parser.add_argument("--min-risk-pct", type=float, default=0.0003)
    parser.add_argument("--stop-buffer-u", type=float, default=0.8)
    parser.add_argument("--roundtrip-fee-pct", type=float, default=0.001)
    parser.add_argument("--windows", default="1m,3m,5m,15m,30m,60m")
    parser.add_argument("--min-group-sample-size", type=int, default=30)
    parser.add_argument("--exclude-near-a1-minutes", type=float, default=5.0)
    parser.add_argument(
        "--baseline-risk-mode",
        choices=("source", "local"),
        default="source",
        help="Random baseline risk denominator: source uses each source A1 risk; local uses random-point proxy width.",
    )
    return parser


def _local_time(ts: float, timezone_name: str) -> str:
    if not ts or ts <= 0:
        return "N/A"
    return datetime.fromtimestamp(float(ts), tz=ZoneInfo(timezone_name)).isoformat()


def _build_data_quality(events: list[Any], klines: list[dict[str, float]], forward_results: list[Any]) -> dict[str, Any]:
    kline_ts = [float(row["timestamp"]) for row in klines if float(row.get("timestamp", 0.0)) > 0]
    event_ts = [float(event.event_ts) for event in events if float(getattr(event, "event_ts", 0.0)) > 0]
    kline_min = min(kline_ts) if kline_ts else 0.0
    kline_max = max(kline_ts) if kline_ts else 0.0
    event_min = min(event_ts) if event_ts else 0.0
    event_max = max(event_ts) if event_ts else 0.0
    events_outside = sum(1 for ts in event_ts if kline_min <= 0 or kline_max <= 0 or ts < kline_min or ts > kline_max)
    rows = [row.to_dict() if hasattr(row, "to_dict") else dict(row) for row in forward_results or []]
    insufficient_15 = {
        row.get("event_key")
        for row in rows
        if int(float(row.get("window_sec", 0))) == 900 and str(row.get("insufficient_future_data")).lower() in {"true", "1"}
    }
    insufficient_60 = {
        row.get("event_key")
        for row in rows
        if int(float(row.get("window_sec", 0))) == 3600 and str(row.get("insufficient_future_data")).lower() in {"true", "1"}
    }
    valid_15 = {
        row.get("event_key")
        for row in rows
        if int(float(row.get("window_sec", 0))) == 900 and str(row.get("insufficient_future_data")).lower() not in {"true", "1"}
    }
    valid_60 = {
        row.get("event_key")
        for row in rows
        if int(float(row.get("window_sec", 0))) == 3600 and str(row.get("insufficient_future_data")).lower() not in {"true", "1"}
    }
    return {
        "kline_min_ts": kline_min,
        "kline_max_ts": kline_max,
        "event_min_ts": event_min,
        "event_max_ts": event_max,
        "events_outside_kline_range": events_outside,
        "events_insufficient_15m_count": len(insufficient_15),
        "events_insufficient_60m_count": len(insufficient_60),
        "valid_events_15m_count": len(valid_15),
        "valid_events_60m_count": len(valid_60),
    }


def _print_time_diagnostics(data_quality: dict[str, Any], kline_timezone: str) -> None:
    kline_min = float(data_quality.get("kline_min_ts", 0.0))
    kline_max = float(data_quality.get("kline_max_ts", 0.0))
    event_min = float(data_quality.get("event_min_ts", 0.0))
    event_max = float(data_quality.get("event_max_ts", 0.0))
    overlap = 0.0
    if event_min and kline_min and kline_max >= event_min and event_max >= kline_min:
        overlap = max(1.0, min(kline_max, event_max) - max(kline_min, event_min))
    print(f"[A1-EDGE-TIME] kline_timezone={kline_timezone}")
    print(f"[A1-EDGE-TIME] kline_min_ts={kline_min} kline_min_local={_local_time(kline_min, kline_timezone)}")
    print(f"[A1-EDGE-TIME] kline_max_ts={kline_max} kline_max_local={_local_time(kline_max, kline_timezone)}")
    print(f"[A1-EDGE-TIME] event_min_ts={event_min} event_min_local={_local_time(event_min, kline_timezone)}")
    print(f"[A1-EDGE-TIME] event_max_ts={event_max} event_max_local={_local_time(event_max, kline_timezone)}")
    print(f"[A1-EDGE-TIME] overlap_sec={overlap}")
    if kline_min and kline_min < 1_500_000_000:
        print("[A1-EDGE-TIME-ERROR] kline timestamps look too small, possible ms/sec double conversion")
    outside = int(data_quality.get("events_outside_kline_range", 0) or 0)
    if outside > 0:
        print(f"[A1-EDGE-TIME-WARN] events_outside_kline_range={outside}")
    if event_min and kline_min and overlap <= 0:
        print("[A1-EDGE-TIME-WARN] no overlap between event timestamps and kline timestamps")


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    events_path = Path(args.events)
    klines_path = Path(args.klines)
    try:
        ZoneInfo(args.kline_timezone)
    except Exception as exc:
        print(f"Error: invalid --kline-timezone: {args.kline_timezone}", file=sys.stderr)
        return 2
    if not events_path.exists():
        print(f"Error: events path does not exist: {events_path}", file=sys.stderr)
        return 2
    if not klines_path.exists():
        print(f"Error: klines path does not exist: {klines_path}", file=sys.stderr)
        return 2
    out_dir = ensure_dir(args.out)
    try:
        klines = read_kline_csv(klines_path, kline_timezone=args.kline_timezone)
    except ValueError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 2
    if not klines:
        print(f"Error: kline CSV is empty or has no valid timestamp rows: {klines_path}", file=sys.stderr)
        return 2
    try:
        windows = parse_windows(args.windows)
        exporter = A1EdgeDatasetExporter()
        events = exporter.load_events(events_path, symbol=args.symbol)
        exporter.export(events, out_dir)
        forward = A1ForwardMetricsAnalyzer(windows, args.min_risk_u, args.min_risk_pct)
        forward_results = forward.analyze(events, klines)
        forward.export(forward_results, out_dir)
        data_quality = _build_data_quality(events, klines, forward_results)
        _print_time_diagnostics(data_quality, args.kline_timezone)
        sampler = RandomBaselineSampler(
            samples_per_event=args.random_samples_per_event,
            random_seed=args.seed,
            exclude_near_a1_minutes=args.exclude_near_a1_minutes,
            windows_sec=windows,
            min_risk_u=args.min_risk_u,
            min_risk_pct=args.min_risk_pct,
            baseline_risk_mode=args.baseline_risk_mode,
        )
        baseline = sampler.sample(events, klines)
        comparator = A1RandomBaselineComparator(min_group_sample_size=args.min_group_sample_size)
        random_summary = comparator.summarize(events, [row.to_dict() for row in forward_results], baseline)
        comparator.export(baseline, random_summary, out_dir)
        simulator = A1HypothesisSimulator(
            stop_buffer_u=args.stop_buffer_u,
            min_risk_u=args.min_risk_u,
            min_risk_pct=args.min_risk_pct,
            roundtrip_fee_pct=args.roundtrip_fee_pct,
            min_group_sample_size=args.min_group_sample_size,
        )
        hypothesis_results = simulator.simulate(events, klines)
        hypothesis_summary = simulator.summarize(hypothesis_results)
        simulator.export(hypothesis_results, hypothesis_summary, out_dir)
        report = A1EdgeReportBuilder(min_group_sample_size=args.min_group_sample_size).build(
            events=[event.to_dict() for event in events],
            forward_metrics=[row.to_dict() for row in forward_results],
            random_baseline=[row.to_dict() for row in baseline],
            random_summary=random_summary,
            hypothesis_results=[row.to_dict() for row in hypothesis_results],
            hypothesis_summary=hypothesis_summary,
            out_dir=out_dir,
            data_quality=data_quality,
        )
    except Exception as exc:
        print(f"Error: failed to analyze A1 edge data: {exc}", file=sys.stderr)
        return 1
    print(f"A1 edge analysis complete: decision={report.decision} out={out_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
